// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khzzuujhlqfipauqgqpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtoenp1dWpobHFmaXBhdXFncXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDA4NTUsImV4cCI6MjA2NjYxNjg1NX0.aUE7ph4zAiK9K3IOIy_wtThTpxvKTfatrP8iynbkZiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);